services:
  pgvector:
    user: "${UID}:${GID}"
    image: pgvector/pgvector:pg17
    container_name: harshal_pgvector
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      PGVECTOR_DB: mydb
      PGVECTOR_USER: myuser
      PGVECTOR_PASSWORD: mypassword
    volumes:
      - ./db_data:/var/lib/postgresql/data
    networks:
      - mydb_pg_network
    ports:
      - "127.0.0.1:8931:5432"
    healthcheck:
      test:
        - CMD
        - pg_isready
        - -U
        - myuser
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  db_data:
    name: db_data

networks:
  mydb_pg_network:
    name: mydb_pg_network
